import { type NextPage } from "next";
import Head from "next/head";
import { useSession } from "next-auth/react";

import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  useEffect(() => {
    if (!sessionData) {
      router.push('/auth/signin ').then(() => {
        console.log('redirected to signin page')
      }).catch((err) => {
        console.log('error redirecting to signin page', err)
      });
    }
  }, [sessionData]);

  return (
    <>
      <Head>
        <title>Q&AI</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
};

export default Home;





